---
- name: Add cron job for root user in LXC container
  hosts: bananapi
  become: true  # Use this to escalate permissions to root
  tasks:

    - name: Add a cron job for root
      cron:
        name: "Goaccess"
        minute: "*/15"
        hour: "*"
        job: "/home/carlos/bin/my_goaccess.sh start"
        state: present

    - name: Add google_domains_ip_refresh.sh to cron
      cron:
        name: "Set ip cloudeflare Domains"
        minute: "*/5"
        hour: "*"
        job: "/home/carlos/bin/google_domains_ip_refresh.sh"
        state: present

    - name: Add anti-goleores iptables rules to cron
      cron:
        name: "IPtables banana anti-goleores"
        minute: "*/15"
        hour: "*"
        job: "/home/carlos/bin/IPtables_banana.sh"
        state: present

    - name: lo de emacs
      command: apt build-dep -y emacs

    - name: Restart docker
      command: /etc/init.d/docker restart

    - name: Install checkinstall
      apt:
        name:
          - libtool-bin
          - checkinstall
          - libtree-sitter0
          - libtree-sitter-dev
          - xclip
          - lsof
          - fail2ban
          - less
        state: present

    - name: Copy jail.local to /etc/fail2ban
      copy:
        src: /home/carlos/.dotfiles/configurations/bananapi/etc/fail2ban/jail.local
        dest: /etc/fail2ban/jail.local
        mode: '0644'
        force: no

    - name: Copy iptables-traefik443.conf to /etc/fail2ban/action.d
      copy:
        src: /home/carlos/.dotfiles/configurations/bananapi/etc/fail2ban/action.d/iptables-traefik443.conf
        dest: /etc/fail2ban/action.d/iptables-traefik443.conf
        mode: '0644'
        force: no

    - name: Copy masscan.conf to /etc/fail2ban/action.d
      copy:
        src: /home/carlos/.dotfiles/configurations/bananapi/etc/fail2ban/action.d/masscan.conf
        dest: /etc/fail2ban/action.d/masscan.conf
        mode: '0644'
        force: no

    - name: Copy sshd.conf to /etc/fail2ban/action.d
      copy:
        src:  /home/carlos/.dotfiles/configurations/bananapi/etc/fail2ban/action.d/sshd.conf
        dest: /etc/fail2ban/action.d/sshd.conf
        mode: '0644' 
        force: no

    - name: Restart fail2ban
      command: /etc/init.d/fail2ban restart
