---

- name: Set up node packages
  hosts: postgres_nodes # here should be tsc-host-1 instead
  become_method: sudo
  become: true
  #vars_prompt:
    #- name: "ansible_become_pass"
      #prompt: "Enter your sudo password in remote server"
      #private: yes


  tasks:

    - name: Set APT to not install recommended packages
      copy:
        dest: /etc/apt/apt.conf.d/01norecommend
        content: |
          APT::Install-Recommends "0";
          APT::Install-Suggests "0";

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages
      become: yes
      become_method: sudo
      apt:
        name:
          - vim
          - net-tools
          - sudo
          - ripgrep
          - fzf
          - python3-pip
          - cron
          - tmux
          - mosh
          - jq
          - telnet
          - netcat-openbsd
        state: present
        install_recommends: no

    - name: Install docker required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
          - bash-completion
        state: present

    - name: Add Docker GPG key
      shell: >
        curl -fsSL https://download.docker.com/linux/debian/gpg |
        gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Ensure Docker sources list file exists
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: touch

    - name: Set up the Docker repository
      lineinfile:
        path: /etc/apt/sources.list.d/docker.list
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - docker-compose-plugin
          - docker-buildx-plugin
        state: present

    - name: Add user {{ banana_username }} to the docker group
      command: usermod -aG docker carlos

    - name: Start and enable Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Update apt package index
      apt:
        update_cache: yes
