---
- name: Set up TSC packages
  hosts: all # here should be tsc-host-1 instead
  become_method: sudo
  become: true
  #vars_prompt:
    #- name: "ansible_become_pass"
      #prompt: "Enter your sudo password in remote server"
      #private: yes


  tasks:
    # - name: apt update
    #   become: yes
    #   command: apt update

    - name: avoid tshark config to block installation #esto es para que no pregunte lo del setuid y se bloquee
      become: yes
      shell: echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections

    - name: Set APT to not install recommended packages
      copy:
        dest: /etc/apt/apt.conf.d/01norecommend
        content: |
          APT::Install-Recommends "0";
          APT::Install-Suggests "0";

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages
      become: yes
      become_method: sudo
      apt:
        name:
          - vim
          - munin
          - munin-node
          - psmisc
          - daemon
          - acl
          - rsyslog-relp
          - apache2
          - php
          - php-gd
          - php-pgsql
          - php-redis
          - ntp
          - gdb
          - net-tools
          - htop
          - iotop
          - ifenslave
          - dcfldd
          - socat
          - apt-offline
          - tshark
          - nvme-cli
          - snmp
          - snmpd
          - libsnmp-dev
          - python3-pip
          - python3-psycopg2
          - python3-pyinotify
          - python3-pil
          - python3-redis
          - python3-joblib
          - python3-pycryptodome
          - python3-scipy
          - python3-networkx
        state: present
        install_recommends: no
